Render front lines from geojson
stepan-anokhin/spb-histmap pull request #19
Opened 2022-01-11 03:55 UTC by vzakhari

2022-01-11 13:07 UTC, stepan-anokhin requested changes
В целом ништяк, надо чуток отрефакторить и разрезолвить конфликты, и можно мёржить!

2022-01-11 13:07 UTC, stepan-anokhin commented on src/model.ts
> +  type : string;
Нужно бы задать enum для типа:
```typescript
enum FrontLineType {
    Polygon = "Polygon",
    Linestring = "Linestring",
}
```
Тайп-чекинг будет лучше.

2022-01-11 13:07 UTC, stepan-anokhin commented on src/model.ts
> +        case "Polygon":
Ну а тут и далее соответственно заюзать этот `enum`

2022-01-11 13:07 UTC, stepan-anokhin commented on src/components/Application/Application.tsx
> +                  <Tooltip sticky>
Предлагаю завести отдельный компонент `FrontLineTooltip`, который будет принимать `frontLine:FrontLine` в качестве параметра. И использовать его в обоих случаях.

2022-01-11 13:07 UTC, stepan-anokhin commented on src/components/Application/Application.tsx
> +            if (frontline.type == "Polygon") {
Можно отрефакторить двумя способами: (1) ввести вспомогательный компонент, который будет принимать `FrontLine` и в зависимости от типа уже рисовать Polygon или Polyline, или (2) создать функцию, которая вернёт нужный компонент по `frontline.type`:
```tsx
const FrontLineComponent = resolveFrontLineComponent(fontline.type);

return <FrontLineComponent positions={front.ine.anchors} />
```

Более развёрнуто эти 2 подхода можно тут глянуть:
https://gist.github.com/stepan-anokhin/65d1e4365ec116fdf328de411d480b7f

2022-01-11 13:07 UTC, stepan-anokhin commented on src/components/Application/Application.tsx
> +                <Polygon positions={frontline.anchors.map((anchor) => (
Можно просто передавать `frontline.anchors` без дополнительных преобразований. 

В TypeScript один тип может быть подтипом другого, если реализует его контракт (например, тот же набор полей) без явного наследования. См: https://www.typescriptlang.org/docs/handbook/type-compatibility.html

2022-01-12 02:02 UTC, vzakhari commented
leaflet оказывается поддерживает GeoJSON - сейчас разбираюсь, удобно ли его будет кастомизировать, например, те же tooltip'ы отображать

https://leafletjs.com/examples/geojson/

2022-01-12 07:35 UTC, stepan-anokhin requested changes
Чуть типы подправить и вливаем =)

2022-01-12 07:35 UTC, stepan-anokhin commented on src/components/Application/Application.tsx
> +  geojsons : Object[];
Лучше `geojsons: GeoJSON.GeoJsonObject;`

2022-01-12 07:35 UTC, stepan-anokhin commented on src/model.ts
> +export function getGeoJSONs(requireContext : __WebpackModuleApi.RequireContext) {
лучше явно указать возвращаемый тип как `GeoJSON.GeoJsonObject`

2022-01-12 07:35 UTC, stepan-anokhin commented on src/components/Application/Application.tsx
> +function renderGeoJSONs(jsons : Object[]) {
Чуть типы подправить: на вход `GeoJSON.GeoJsonObject[]`, на выход `React.ReactNode`

2022-01-13 02:43 UTC, vzakhari commented
Двинул в #20 - так было проще конфликты разрешить :)

2022-01-13 05:27 UTC, closed without merging